name: Go
on: [push]
jobs:
  macos:
    # name: build
    strategy:
      matrix:
        # go: [1.12.x, 1.13.x]
        os: [macOS-latest ] # ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go 1.21.0
        uses: actions/setup-go@v1
        with:
          go-version: 1.21.0
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          cd examples/key
          go build -o keyboard -v ./...
          ls -la

  windows:
    # name: build
    strategy:
      matrix:
        # go: [1.12.x, 1.13.x]
        os: [ windows-latest ] # ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go 1.21.0
        uses: actions/setup-go@v1
        with:
          go-version: 1.21.0
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          cd examples/key
          go build -o keyboard.exe -v ./...
          dir

  ubuntu:
    # name: build
    strategy:
      matrix:
        # go: [1.12.x, 1.13.x]
        os: [ ubuntu-latest ] # ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go 1.21.0
        uses: actions/setup-go@v1
        with:
          go-version: 1.21.0
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: build
        run: |
          apt install -y gcc libc6-dev libx11-dev xorg-dev libxtst-dev xsel xclip libpng++-dev xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev
          cd examples/key
          go build -o keyboard -v ./...
          ls -la