name: Build
on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build-latest:
    # name: build
    strategy:
      matrix:
        # go: [1.12.x, 1.13.x]
        os: [macos-latest, windows-latest, ubuntu-latest] # ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go 1.21.0
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.0
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          go build -v ./...

      - name: Build
        run: go build -v .
      - name: Test
        run: go test -v robot_info_test.go